package org.corella.accesoDatos.practica2.utils;

public class Constants {
    public enum Provincias {
        ALAVA, ALBACETE, ALICANTE, ALMERIA, ASTURIAS, AVILA,
        BADAJOZ, BALEARES, BARCELONA, BURGOS, CACERES, CADIZ,
        CANTABRIA, CASTELLON, CEUTA, CIUDAD_REAL, CORDOBA,
        CUENCA, GERONA, GRANADA, GUADALAJARA, GUIPUZCOA,
        HUELVA, HUESCA, JAEN, LA_CORUNA, LA_RIOJA, LAS_PALMAS,
        LEON, LERIDA, LUGO, MADRID, MALAGA, MELILLA, MURCIA,
        NAVARRA, ORENSE, PALENCIA, PONTEVEDRA, SALAMANCA,
        SEGOVIA, SEVILLA, SORIA, TARRAGONA, SANTA_CRUZ_DE_TENERIFE,
        TERUEL, TOLEDO, VALENCIA, VALLADOLID, VIZCAYA, ZAMORA, ZARAGOZA
    }

    public enum Irpf {
        IRPF_5, IRPF_10, IRPF_15
    }

    public enum Fondo {
        PENSIONES, INVERSIÓN
    }
}
